"""
This script contains hard coded urls and text that corresponds with a certain error.
It is used in the scraping.py script
"""

# EMPTY P-TAG URL ERRORS
empty_ptag_url_errors = {'404 Page not found': ['feeds.foxnews.com/', 'pjmedia.com/blog', 'weny.com',
                                                'americantoday.news','supremepatriot.com','highschoolsports.al.com',
                                                'www.philly.com','rightalert.com/','InfiniteUnknown/','newsbreakapp.com'],
                         'Article has been archived': ['delmarvanow.com', 'fosters.com', 'seacoastonline.com',
                                                       'capecodtimes.com','recordnet.com','www.progress-index.com',
                                                       'gainesville.com','www.dispatch.com','nwfdailynews.com',
                                                       'theledger.com', 'ocala.com', 'tuscaloosanews.com',
                                                       'newsherald.com','citizenfreepress.com','www.blufftontoday.com',
                                                       'newschief.com','kuow.org','southernkitchen.com',
                                                       'telegram.com', 'providencejournal.com', 'staugustine.com',
                                                       'cjonline.com','lubbockonline.com','www.heraldnews.com/',
                                                       'columbiadailyherald','jsonline.com',
                                                       'jacksonville.com', 'houmatoday.com', 'zerohedge.com',
                                                       'heraldtribune.com','rssfeeds.azcentral.com',
                                                       'uticaod.com','rssfeeds.cincinnati.com',
                                                       'palmbeachpost.com', 'palmbeachdailynews.com',
                                                       'enterprisenews.com','rssfeeds.burlingtonfreepress',
                                                       'waynedupree.com',
                                                       'patriotledger.com', 'recordonline.com',
                                                       'heraldnews.com', 'southcoasttoday.com',
                                                       'dailycommercial.com', 'sj-r.com', 'pjstar.com',
                                                       'hollandsentinel.com',

                                                       'feeds.bizjournals.com', 'timesonline', 'progress-index',
                                                       'tauntongazette',
                                                       'metrowestdaily',
                                                       'norwichbulletin.com', 'savannahnow.com', 'breakingtimes.com',
                                                        'northjersey.com',
                                                       'news-journalonline', 'goerie.com', 'southcoasttoday',
                                                       'vvdailypress',
                                                       'sentinel-standard',
                                                       'eveningtribune', 'blufftontoday', 'amestrib.com',
                                                       'goupstate.com',
                                                       'mystatesman.com', 'onlineathens',
                                                       'statesman', 'rrstar.com', 'cantonrep.com', 'thetimesnews',
                                                       'starnewsonline.com', 'obama.trendolizer'
                                                       ],
                         'Article not found': [ 'unleashthebeef.com', 'the-review',
                                               'dailycommerical.com','mrcblog.com',
                                               'fayobserver.com',
                                               'liberalmountain.com',

                                               'upstract.com','israelnationalnews.com',
                                               'commdiginews.com', 'ranker.com', 'ipolitics.ca',
                                               'forums.hannity.com', 'bients.com'],
                         'Video/ Image content only': ['limportant.fr', 'feeds.bet.com/~r','wkyufm.org',
                                                       'gma/videos/', '/videos/','wnyc.org','/gallery/',
                                                       '/video/', 'nbcwashington.com','wlrn.org',
                                                       'forbes.com/pictures/','issuu.com/','rssfeeds.usatoday.com',
                                                       'espn.go.com/espnradio/','/video/']
                         }

empty_ptag_text_errors = {'Article not found': ['Sorry, we can’t seem to find the page you’re looking for'.lower(),
                                                'page which is currently unavailable','Temporary unavailable. Sorry!'.lower(),
                                                "Sorry, we couldn't find that page.".lower(),
                                                'your request resulted in an error','default backend - 404'],
                          'Blocked from website': ['whitelist your IP'.lower(), 'Bot Protection Firewall'.lower(),
                                                   'Access Denied'.lower(),'you were blocked',
                                                   'request unsuccessful', 'potential automated action detected',
                                                   'blocked your ip',
                                                   'The action you just performed triggered the security solution'.lower(),
                                                   'Sorry but something about this request looked a bit suspicious, and we block suspicious'.lower()]
                          }

""" NEVER SCRAPABALE ERRORS """
n_scrapable_url_errors = {'Not scrapable content': ['farminguk.com', 'google.com/maps/', 'google.com/search?',
                                                    'http://www.bbc.co.uk/programmes/',
                                                    'insideedition.com/videos/', 'itunes.apple.com', 'slideshare.net',
                                                    'docs.google.com', 'nymag.com/tags/','documentcloud.org/documents',
                                                    'photos.google.com'],
                          'Video/ Image content only': ['www.youtube.com/watch', 'instagram.com', 'pinterest.com',
                                                        'https://xkcd.com/','//youtu.be/',
                                                        'photos.prnewswire.com', 'worldstarhiphop.com/videos/video',
                                                        'flickr.com', 'beta.prx.org'],
                          'Website is no longer maintained': ['www.examiner.com', 'liberalplug.com','o4anews.com',
                                                              'leftwingnation.org', 'learnprogress.org',
                                                              'forwardprogressives.com', 'anotherdayintheempire.com',
                                                              'teapartytribune.com', 'madpatriots.com',
                                                              'winningdemocrats.com', 'hermancain.com', 'gloria.tv',
                                                              'viralliberty.com', 'usanewsflash',
                                                              'conservativedailyreview.com',
                                                              'readconservatives.news', 'politicalsitenews.com',
                                                              'usatwentyfour.com', 'ufpnews.com',
                                                              'kinjaroundup.kinja.com',
                                                              'sourcesnews.com', 'hillary4prisoner.com',
                                                              'hangthebankers.com', 'patriothangout.com',
                                                              'bloodyrubbish.com', 'conservative101.com',
                                                              'dailyrushbo.com','.ozy.com'
                                                              'liveleak.com', 'the-daily-record','departedmedia.com']
                          }

""" SOUP CONTENTS ERRORS """
soup_contents_text_errors = {'403 Forbidden': ['403 forbidden', '403 error',
                                               '403 - forbidden'],
                             '404 Page not found': ['page not found', 'was not found on this server',
                                                    'https status: 404 (not found)','http status: 404 (not found)',
                                                    'Error 503', 'page unavailable','page cannot be displayed.',
                                                    '404 not found','404: not found',
                                                    "The gallery you're looking for is no longer up-to-date".lower(),
                                                    'Feed Address: HTTP Error (Code) and Message: (404) null'.lower(),
                                                     'post not available',' View the current page or another snapshot:'.lower(),
                                                    'reference #18.',
                                                    'search privacy notice','404 - file not found','"status" : 404',
                                                    'Username or Email Address Remember Me  Lost your password? ← Go to Fellowship Of The Minds'.lower()],
                             '451 Unavailable for legal reasons': ['content not available in your', '451: unavailable',
                                                                   'is not available in your region',
                                                                   'unable to allow international traffic',
                                                                   'is not available in your country',
                                                                   '451 unavailable for legal reasons',
                                                                   'currently unavailable in most european countries',
                                                                   'is not currently available in your location'],
                             'Article behind a paywall or login page': ['The Advocatesubscription panel'.lower(),
                                                                        'full story, subscribe now',
                                                                        'fellowship of the minds',
                                                                        'The web browser you are using does not support modern websites. You are using an outdated browser. Please upgrade your browser to improve your experience.'.lower(),
                                                                        'please wait while we attempt to load the request page',
                                                                        'please login below or register an account'],
                             'Article not found': ['please correct the error and try again',
                                                   'please visit to new hosted site', 'this page is missing',
                                                   'the page you requested is unavailable', "Article not found".lower(),
                                                   'for some reason reddit can\'t be reached',
                                                   'this page is currently unavailable',
                                                   'Aus irgendeinem Grund kann Reddit leider nicht erreicht werden.'.lower(),
                                                   'Sorry, we can’t seem to find the page you’re looking for'.lower(),
                                                   'page which is currently unavailable',
                                                   "Sorry, we couldn't find that page.".lower(),
                                                   'your request resulted in an error'
                                                   ],
                             'Must enable cookies to access site': ['Enable JavaScript and cookies to continue'.lower(),
                                                                    'enable javascript', 'please enable js',
                                                                    'ensure javascript is enabled',
                                                                    'Please enable Cookies and reload the page. Completing the CAPTCHA proves you are a human'.lower()],
                             'Blocked from website':['whitelist your IP'.lower(), 'Bot Protection Firewall'.lower(),
                                                   'Access Denied'.lower(),'you were blocked',
                                                     'Refresh the page or contact the site owner to request access. C'.lower(),
                                                   'request unsuccessful', 'potential automated action detected',
                                                   'blocked your ip','Refresh the page or contact the site owner to request access. Copy and paste the Ray ID when you contact the site owner'.lower(),
                                                   'The action you just performed triggered the security solution'.lower(),
                                                   'Sorry but something about this request looked a bit suspicious, and we block suspicious'.lower()]
                             }
